spring:
  application:
    name: order-service
  lifecycle:
    timeout-per-shutdown-phase: 15s #durée max pour terminer le traitement des req en cours avant arrêt
  r2dbc:
    username: user
    password: password
    url: r2dbc:postgresql://localhost:5432/polardb_order
    pool:
      max-create-connection-time: 2s # temps max pour obtenir une connexion depuis le pool
      initial-size: 5
      max-size: 10 # défaut
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5432/polardb_order

server:
  port: 9002
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
polar:
  catalog-service-uri: "http://localhost:9001"
  #externalisation des valeurs de configuration de la résilience Reactor
  timeout: 3
  max-retry: 3
  retry-backoff: 100
